{"uid":"4b4757e66a1912dae1a509f688f20b0f","children":[{"name":"Product defects","children":[{"name":"\n\nmock: Unexpected Method Call\n-----------------------------\n\nGetByPhone(context.todoCtx,*dto.GetEmployeeRequest)\n\t\t0: context.todoCtx{emptyCtx:context.emptyCtx{}}\n\t\t1: &dto.GetEmployeeRequest{PhoneNumber:\"123\"}\n\nThe closest call I have is: \n\nGetByPhone(context.todoCtx,*dto.LoginEmployeeRequest)\n\t\t0: context.todoCtx{emptyCtx:context.emptyCtx{}}\n\t\t1: &dto.LoginEmployeeRequest{PhoneNumber:\"123\", Password:\"89t3n82rdjy437dr\"}\n\n\nDiff: 0: PASS:  (context.todoCtx=context.TODO) == (context.todoCtx=context.TODO)\n\t1: FAIL:  (*dto.GetEmployeeRequest=&{123}) != (*dto.LoginEmployeeRequest=&{123 89t3n82rdjy437dr})","children":[{"name":"[LoginEmployee] Incorrect password","uid":"a7a956bc297914ee","parentUid":"366c6cc60d6cd70f0b05b9ed10c2fdf7","status":"failed","time":{"start":1728203957118,"stop":1728203957119,"duration":1},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[],"tags":["auth","login"]}],"uid":"366c6cc60d6cd70f0b05b9ed10c2fdf7"},{"name":"\nassert: mock: I don't know what to return because the method call was unexpected.\n\tEither do Mock.On(\"GetByPhone\").Return(...) first, or remove the GetByPhone() call.\n\tThis method was unexpected:\n\t\tGetByPhone(context.todoCtx,*dto.GetEmployeeRequest)\n\t\t0: context.todoCtx{emptyCtx:context.emptyCtx{}}\n\t\t1: &dto.GetEmployeeRequest{PhoneNumber:\"123\"}\n\tat: [/home/runner/work/Testing/Testing/internal/storage/mocks/EmployeeStorage.go:69 /home/runner/work/Testing/Testing/internal/service/auth.go:117 /home/runner/work/Testing/Testing/internal/service/auth_test.go:180 /home/runner/go/pkg/mod/github.com/ozontech/allure-go/pkg/framework@v0.6.32/core/common/steps.go:27 /home/runner/work/Testing/Testing/internal/service/auth_test.go:130]","children":[{"name":"[LoginEmployee] Correct request","uid":"ea19dd27bd7c641e","parentUid":"5348db941982b12c6f73119f97fa8c8b","status":"failed","time":{"start":1728203957118,"stop":1728203958218,"duration":1100},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[],"tags":["auth","login"]}],"uid":"5348db941982b12c6f73119f97fa8c8b"},{"name":"\n\nmock: Unexpected Method Call\n-----------------------------\n\nGetByPhone(context.todoCtx,*dto.GetEmployeeRequest)\n\t\t0: context.todoCtx{emptyCtx:context.emptyCtx{}}\n\t\t1: &dto.GetEmployeeRequest{PhoneNumber:\"7n8c8937d38d73\"}\n\nThe closest call I have is: \n\nGetByPhone(context.todoCtx,*dto.LoginEmployeeRequest)\n\t\t0: context.todoCtx{emptyCtx:context.emptyCtx{}}\n\t\t1: &dto.LoginEmployeeRequest{PhoneNumber:\"7n8c8937d38d73\", Password:\"21e12\"}\n\n\nDiff: 0: PASS:  (context.todoCtx=context.TODO) == (context.todoCtx=context.TODO)\n\t1: FAIL:  (*dto.GetEmployeeRequest=&{7n8c8937d38d73}) != (*dto.LoginEmployeeRequest=&{7n8c8937d38d73 21e12})","children":[{"name":"[LoginEmployee] Incorrect phone number","uid":"935bb2417ddfc0f1","parentUid":"b1f6c9ee5ee3436aa05e5bc98e222bf9","status":"failed","time":{"start":1728203957118,"stop":1728203957125,"duration":7},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[],"tags":["auth","login"]}],"uid":"b1f6c9ee5ee3436aa05e5bc98e222bf9"}],"uid":"8fb3a91ba5aaf9de24cc8a92edc82b5d"}],"name":"categories"}