{"uid":"ea19dd27bd7c641e","name":"[LoginEmployee] Correct request","fullName":"TestRunner/AuthSuite/Test_Auth_LoginEmployee3","historyId":"dd9765cf29337180114146efb07a914e","time":{"start":1728203957118,"stop":1728203958218,"duration":1100},"status":"failed","statusMessage":"\nassert: mock: I don't know what to return because the method call was unexpected.\n\tEither do Mock.On(\"GetByPhone\").Return(...) first, or remove the GetByPhone() call.\n\tThis method was unexpected:\n\t\tGetByPhone(context.todoCtx,*dto.GetEmployeeRequest)\n\t\t0: context.todoCtx{emptyCtx:context.emptyCtx{}}\n\t\t1: &dto.GetEmployeeRequest{PhoneNumber:\"123\"}\n\tat: [/home/runner/work/Testing/Testing/internal/storage/mocks/EmployeeStorage.go:69 /home/runner/work/Testing/Testing/internal/service/auth.go:117 /home/runner/work/Testing/Testing/internal/service/auth_test.go:180 /home/runner/go/pkg/mod/github.com/ozontech/allure-go/pkg/framework@v0.6.32/core/common/steps.go:27 /home/runner/work/Testing/Testing/internal/service/auth_test.go:130]","statusTrace":"\n\nassert: mock: I don't know what to return because the method call was unexpected.\n\tEither do Mock.On(\"GetByPhone\").Return(...) first, or remove the GetByPhone() call.\n\tThis method was unexpected:\n\t\tGetByPhone(context.todoCtx,*dto.GetEmployeeRequest)\n\t\t0: context.todoCtx{emptyCtx:context.emptyCtx{}}\n\t\t1: &dto.GetEmployeeRequest{PhoneNumber:\"123\"}\n\tat: [/home/runner/work/Testing/Testing/internal/storage/mocks/EmployeeStorage.go:69 /home/runner/work/Testing/Testing/internal/service/auth.go:117 /home/runner/work/Testing/Testing/internal/service/auth_test.go:180 /home/runner/go/pkg/mod/github.com/ozontech/allure-go/pkg/framework@v0.6.32/core/common/steps.go:27 /home/runner/work/Testing/Testing/internal/service/auth_test.go:130]","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[],"testStage":{"status":"failed","statusMessage":"\nassert: mock: I don't know what to return because the method call was unexpected.\n\tEither do Mock.On(\"GetByPhone\").Return(...) first, or remove the GetByPhone() call.\n\tThis method was unexpected:\n\t\tGetByPhone(context.todoCtx,*dto.GetEmployeeRequest)\n\t\t0: context.todoCtx{emptyCtx:context.emptyCtx{}}\n\t\t1: &dto.GetEmployeeRequest{PhoneNumber:\"123\"}\n\tat: [/home/runner/work/Testing/Testing/internal/storage/mocks/EmployeeStorage.go:69 /home/runner/work/Testing/Testing/internal/service/auth.go:117 /home/runner/work/Testing/Testing/internal/service/auth_test.go:180 /home/runner/go/pkg/mod/github.com/ozontech/allure-go/pkg/framework@v0.6.32/core/common/steps.go:27 /home/runner/work/Testing/Testing/internal/service/auth_test.go:130]","statusTrace":"\n\nassert: mock: I don't know what to return because the method call was unexpected.\n\tEither do Mock.On(\"GetByPhone\").Return(...) first, or remove the GetByPhone() call.\n\tThis method was unexpected:\n\t\tGetByPhone(context.todoCtx,*dto.GetEmployeeRequest)\n\t\t0: context.todoCtx{emptyCtx:context.emptyCtx{}}\n\t\t1: &dto.GetEmployeeRequest{PhoneNumber:\"123\"}\n\tat: [/home/runner/work/Testing/Testing/internal/storage/mocks/EmployeeStorage.go:69 /home/runner/work/Testing/Testing/internal/service/auth.go:117 /home/runner/work/Testing/Testing/internal/service/auth_test.go:180 /home/runner/go/pkg/mod/github.com/ozontech/allure-go/pkg/framework@v0.6.32/core/common/steps.go:27 /home/runner/work/Testing/Testing/internal/service/auth_test.go:130]","steps":[{"name":"Success","time":{"start":1728203957132,"stop":1728203958218,"duration":1086},"status":"passed","steps":[{"name":"ASSERT: No Error","time":{"start":1728203958217,"stop":1728203958217,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[{"name":"Actual","value":"<nil>"}],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":true}],"attachments":[],"parameters":[{"name":"ctx","value":"context.TODO"},{"name":"request","value":"&{PhoneNumber:123 Password:21e12}"}],"shouldDisplayMessage":false,"stepsCount":1,"attachmentsCount":0,"hasContent":true}],"attachments":[],"parameters":[],"shouldDisplayMessage":true,"stepsCount":2,"attachmentsCount":0,"hasContent":true},"afterStages":[],"labels":[{"name":"language","value":"go1.23.1"},{"name":"framework","value":"Allure-Go@v0.6.0"},{"name":"host","value":"fv-az847-791"},{"name":"thread","value":"TestRunner/AuthSuite/Test_Auth_LoginEmployee3"},{"name":"suite","value":"AuthSuite"},{"name":"package","value":"course/internal/service_test.TestRunner"},{"name":"tag","value":"auth"},{"name":"tag","value":"login"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Product defects","matchedStatuses":[],"flaky":false}],"history":{"statistic":{"failed":2,"broken":0,"skipped":0,"passed":0,"unknown":0,"total":2},"items":[{"uid":"d948c86338bbf3d2","reportUrl":"https://pstpn.github.io/Testing/14//#testresult/d948c86338bbf3d2","status":"failed","statusDetails":"\nassert: mock: I don't know what to return because the method call was unexpected.\n\tEither do Mock.On(\"GetByPhone\").Return(...) first, or remove the GetByPhone() call.\n\tThis method was unexpected:\n\t\tGetByPhone(context.todoCtx,*dto.GetEmployeeRequest)\n\t\t0: context.todoCtx{emptyCtx:context.emptyCtx{}}\n\t\t1: &dto.GetEmployeeRequest{PhoneNumber:\"123\"}\n\tat: [/home/runner/work/Testing/Testing/internal/storage/mocks/EmployeeStorage.go:69 /home/runner/work/Testing/Testing/internal/service/auth.go:117 /home/runner/work/Testing/Testing/internal/service/auth_test.go:180 /home/runner/go/pkg/mod/github.com/ozontech/allure-go/pkg/framework@v0.6.32/core/common/steps.go:27 /home/runner/work/Testing/Testing/internal/service/auth_test.go:130]","time":{"start":1728203504142,"stop":1728203505147,"duration":1005}}]},"tags":["auth","login"]},"source":"ea19dd27bd7c641e.json","parameterValues":[]}